# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.coherify.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

kramdown:
  input: GFM
